spring:
   profiles:
      active:
        - dev
---
server:
  port: 8202

spring:
  profiles: dev
  application:
      name: springcloud-config-client

eureka:
 client:
  service-url:
    defaultZone: http://admin:zhzy@localhost:7001/eureka
    
info:
  app.name: springcloud-config-client-dev3
  company.name: com.zhzy
---
server:
  port: 8103

spring:
  profiles: beta
  application:
    name: springcloud-config-client

eureka:
 client:
  service-url:
    defaultZone: http://admin:zhzy@localhost:7001/eureka

info:
  app.name: springcloud-config-client-dev3
  company.name: com.zhzy
